# Generated by Django 4.2.2 on 2023-06-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0002_alter_registrationform_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='otp',
            field=models.IntegerField(default=162012),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='dob',
            field=models.CharField(max_length=10),
        ),
    ]
